# Generated by Django 5.1.6 on 2026-01-14 20:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان العرض')),
                ('car_name', models.CharField(max_length=150, verbose_name='اسم السيارة')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر القديم')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الجديد')),
                ('image', models.ImageField(upload_to='offers/', verbose_name='صورة السيارة')),
                ('description', models.TextField(verbose_name='وصف العرض')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ بداية العرض')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ نهاية العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='عرض نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عرض',
                'verbose_name_plural': 'العروض',
                'ordering': ['-created_at'],
            },
        ),
    ]
