# Generated by Django 5.1.6 on 2026-01-14 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='offers/gallery/', verbose_name='صورة إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='offers.offer', verbose_name='العرض')),
            ],
            options={
                'verbose_name': 'صورة عرض',
                'verbose_name_plural': 'صور العرض',
            },
        ),
    ]
