# Generated by Django 5.1.6 on 2026-01-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='offers/banners/', verbose_name='صورة عنوان العرض (للواجهة)'),
        ),
    ]
