# Generated by Django 5.1.6 on 2026-01-16 09:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_offer_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='banner_image',
        ),
        migrations.AddField(
            model_name='offer',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.8, max_digits=2, verbose_name='التقييم ⭐'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(upload_to='offers/', verbose_name='الصورة الرئيسية'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
