# Generated by Django 5.1.6 on 2026-01-16 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_remove_offer_banner_image_offer_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='offer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='offer',
            name='car_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(upload_to='offers/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='new_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='old_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='offerimage',
            name='image',
            field=models.ImageField(upload_to='offers/gallery/'),
        ),
        migrations.AlterField(
            model_name='offerimage',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='offers.offer'),
        ),
    ]
