# Generated by Django 5.1.6 on 2026-01-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_alter_offerimage_options_remove_offer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف العرض'),
        ),
        migrations.AddField(
            model_name='offer',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2, verbose_name='التقييم'),
        ),
    ]
