# Generated by Django 6.0 on 2025-12-31 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='الماركة')),
                ('model', models.CharField(max_length=100, verbose_name='الموديل')),
                ('year', models.PositiveIntegerField(verbose_name='سنة الصنع')),
                ('mileage', models.PositiveIntegerField(verbose_name='الكيلومتراج (كم)')),
                ('power', models.CharField(max_length=50, verbose_name='القوة (حصان)')),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('gasoline', 'Gasoline'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], max_length=20, verbose_name='نوع الوقود')),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=20, verbose_name='ناقل الحركة')),
                ('doors', models.PositiveSmallIntegerField(verbose_name='عدد الأبواب')),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used')], max_length=10, verbose_name='الحالة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('image', models.ImageField(upload_to='cars/', verbose_name='الصورة الرئيسية')),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=10, verbose_name='حالة الإعلان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='voitures/')),
                ('marque', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/gallery/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
        ),
    ]
